- name: test become
  hosts: all

  tasks:
    - name: Test become
#      become_user: admin
      become: yes
      command: apt-get update
      register: the_user

    - name: Debug become
      debug:
        msg: "{{ the_user }}"