- hosts: all

  tasks:
  - name: Update apt packages    
    apt:      
      update_cache: yes
      cache_valid_time: 8400 # 1 day
    become: true

  - name: Upgrade apt packages
    apt:
      upgrade: yes
    become: true