- hosts: all
  become: yes

  tasks:
  - name: Update apt packages    
    apt:      
      update_cache: yes
      cache_valid_time: 8400 # 1 day

  - name: Upgrade apt packages
    apt:
      upgrade: yes