- hosts: all
  sudo: yes

  tasks:
  - name: Update apt packages
    sudo: no
    apt:      
      update_cache: yes
      cache_valid_time: 8400 # 1 day

  - name: Upgrade apt packages
    apt:
      upgrade: yes