- hosts: all

  tasks:
  - name: Update apt packages
    shell: sudo apt-get update
#    become: yes
#    become_user: larisa
#    apt:      
#      update_cache: yes
#      cache_valid_time: 8400 # 1 day

  - name: Upgrade apt packages
    become: yes
    apt:
      upgrade: yes