- hosts: all

  tasks:
  - name: Update apt packages
    become: yes
    become_method: sudo
    apt:      
      update_cache: yes
#      cache_valid_time: 8400 # 1 day

  - name: Upgrade apt packages
    become: yes
	become_method: sudo
    apt:
      upgrade: yes