- hosts: all

  tasks:
  - name: Update apt packages
    become: true
    apt:      
      update_cache: yes
      cache_valid_time: 8400 # 1 day

  - name: Upgrade apt packages
    become: true
    become_methid: sudo
    become_user: admin
    apt:
      upgrade: yes