- hosts: all
  become: true

  tasks:
  - name: Update and upgrade apt packages
    apt:      
      update_cache: yes

  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
#cache_valid_time: 8400 # 1 day