- hosts: all

  tasks:
  - name: Update apt packages
    become: true
    apt:      
      update_cache: yes

  - name: Upgrade apt packages
    apt:
      upgrade: yes
#cache_valid_time: 8400 # 1 day