---

- hosts: all
  tasks:

  - name: install zabbix-agent
    apt:
      name: zabbix-agent
      state: present

  - name: copy zabbix configuration file
#    copy: src=./conf/zabbix_agentd.conf dest=/etc/zabbix_agentd.conf seuser=system_u
    copy: 
      src: /etc/zabbix/zabbix_agentd.conf 
      dest: /etc/zabbix/zabbix_agentd.conf

    notify:
      - Start Zabbix-agent

  handlers:
  - name: Start zabbix-agent
    service: 
      name: zabbix-agent 
      state: started 
      enabled: yes