---
- name: Converge
  hosts: all
  pre_tasks:
    - name: "Installing packages on Debian family"
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - net-tools
      when:
        - ansible_os_family == 'Debian'

  roles:
    - role: ansible-zabbix-agent
      zabbix_agent_server: 192.168.0.27
      zabbix_agent_serveractive: 192.168.0.27
#      zabbix_agent_listenip: 0.0.0.0
#      zabbix_agent_tlsconnect: psk
#      zabbix_agent_tlsaccept: psk
#      zabbix_agent_tlspskidentity: my_Identity
#      zabbix_agent_tlspskfile: /data/certs/zabbix.psk
#      zabbix_agent_tlspsk_secret: 97defd6bd126d5ba7fa5f296595f82eac905d5eda270207a580ab7c0cb9e8eab

