---

- hosts: all
  tasks:

  - name: install zabbix-agent
    apt:
      name: zabbix-agent
      state: present

#  - name: copy zabbix configuration file
#    copy: src=./conf/zabbix_agentd.conf dest=/etc/zabbix_agentd.conf seuser=system_u
#    copy: 
#      src: /etc/zabbix/zabbix_agentd.conf 
#      dest: /etc/zabbix/zabbix_agentd.conf

  - name: remove default config
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      line: Server=127.0.0.1
      state: absent

  - name: config agent
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      line: Server=192.168.0.27
      state: present

    notify:
      - Start Zabbix-agent

  handlers:
  - name: Start zabbix-agent
    service: 
      name: zabbix-agent 
      state: started 
      enabled: yes