---

- hosts: all
  tasks:

  - name: install zabbix-agent
    apt:
      name: zabbix-agent
      state: present

#  - name: copy zabbix configuration file
#    copy: src=./conf/zabbix_agentd.conf dest=/etc/zabbix_agentd.conf seuser=system_u
#    copy: 
#      src: /etc/zabbix/zabbix_agentd.conf 
#      dest: /etc/zabbix/zabbix_agentd.conf

  - name: Add user zabbix to group adm
    user:
      name: zabbix
      group: adm
    become: yes

  - name: Stop zabbix-agent
    service: 
      name: zabbix-agent 
      state: stopped 
    ignore_errors: yes

  - name: remove default config
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      line: Server=127.0.0.1
      state: absent

  - name: config agent
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      line: Server=192.168.0.27
      state: present

  - name: Start zabbix-agent
    service: 
      name: zabbix-agent 
      state: started 
      enabled: yes