---

- hosts: all
  tasks:

  - name: Stop zabbix-agent
    service: 
      name: zabbix-agent 
      state: stopped 
    ignore_errors: yes

  - name: install zabbix-agent
    apt:
      name: zabbix-agent
      state: latest

#  - name: copy zabbix configuration file
#    copy: src=./conf/zabbix_agentd.conf dest=/etc/zabbix_agentd.conf seuser=system_u
#    copy: 
#      src: /etc/zabbix/zabbix_agentd.conf 
#      dest: /etc/zabbix/zabbix_agentd.conf

#	This fails with access error !!! not working! 
#  - name: Add user zabbix to group adm
#    become: yes
#    become_method: sudo
#    become_user: admin
#    user:
#      name: zabbix
#      state: present
#      group: adm

# sudo stuck on prompt
#  - name: Add user zabbix to group adm
#    become: yes
#    shell: sudo adduser zabbix adm

  - name: Stop zabbix-agent
    service: 
      name: zabbix-agent 
      state: stopped 
    ignore_errors: yes

  - name: remove default config
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      line: Server=127.0.0.1
      state: absent

  - name: remove default config
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      line: ServerActive=127.0.0.1
      state: absent

  - name: config agent Server
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      line: Server=192.168.0.27
      state: present

  - name: config agent ServerActive
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      line: ServerActive=192.168.0.27
      state: present

  - name: Start zabbix-agent
    service: 
      name: zabbix-agent 
      state: started 
      enabled: yes